export { default as SectionHomeHero } from "./section.home.hero";
export { default as SectionHomeValues } from "./section.home.values";
export { default as SectionHomeCollection } from "./section.home.collection";
export { default as SectionHomePicks } from "./section.home.picks";
export { default as SectionHomeProducts } from "./section.home.products";
export { default as SectionHomeRitual } from "./section.home.ritual";
export { default as SectionHomePalette } from "./section.home.palette";
export { default as SectionHomeStory } from "./section.home.story";
export { default as SectionHomeTestimonials } from "./section.home.testimonials";